environment:
  matrix:
    - PYTHON: "C:/Python27"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "build"
      PYTHON_VERSION: "2.7"
    - PYTHON: "C:/Python34"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "build"
      PYTHON_VERSION: "3.4"

install:
  - git submodule update --init --recursive
  - "%PYTHON%/python.exe find_version.py" # Captures Tesseract version
  - "%PYTHON%/python.exe" -m pip install --upgrade pip
before_build:
  # Tesseract setup
  - cd tesseract
  - curl -fsS -L -o cppan.zip https://cppan.org/client/cppan-master-Windows-client.zip
  - 7z x cppan.zip
  - set PATH=%PATH%;%cd%
  - cppan # dummy run to create %USERPROFILE%\.cppan\cppan.yml
  - ps: 'Add-Content $env:USERPROFILE\.cppan\cppan.yml "`n`nvar_check_jobs: 1`n"'
  - ps: 'Add-Content $env:USERPROFILE\.cppan\cppan.yml "`n`nbuild_warning_level: 0`n"'
  - ps: 'Add-Content $env:USERPROFILE\.cppan\cppan.yml "`n`nbuild_system_verbose: false`n"'  

build_script:
  - mkdir build
  - cd build
  #- cmd: 'echo local_settings: > cppan.yml'
  #- cmd: 'echo     generator: %generator% >> cppan.yml'
  #- cmd: 'echo     use_shared_libs: true >> cppan.yml'
  #- cppan --build ..
  - cmake .. -G "%BUILD_ENV%" -DBUILD_TRAINING_TOOLS=Off -DAPPVEYOR=1
  - cmake --build . --config Release

test_script:
  - dir