environment:
  matrix:
  - PYTHON: "C:/Python27"
    BUILD_ENV: "Visual Studio 14"
    BUILD_DIR: "build"
    PYTHON_VERSION: "2.7"

install:
  - |
    git submodule update --init --recursive
    "%PYTHON%/python.exe" find_version.py
    "%PYTHON%/python.exe" -m pip install --upgrade pip

before_build:
- cd tesseract # Tesseract setup
- curl -fsS -L -o cppan.zip https://cppan.org/client/cppan-master-Windows-client.zip
- 7z x cppan.zip
- set PATH=%PATH%;%cd%
- cppan # dummy run to create %USERPROFILE%\.cppan\cppan.yml
- ps: 'Add-Content $env:USERPROFILE\.cppan\cppan.yml "`n`nvar_check_jobs: 1`n"'
- ps: 'Add-Content $env:USERPROFILE\.cppan\cppan.yml "`n`nbuild_warning_level: 0`n"'
- ps: 'Add-Content $env:USERPROFILE\.cppan\cppan.yml "`n`nbuild_system_verbose: false`n"'

build_script:
- |
  mkdir build
  cd build
  cmake .. -G "%BUILD_ENV%" -DBUILD_TRAINING_TOOLS=Off -DAPPVEYOR=1
  cmake --build . --config Release

  cd ../..
  mkdir include\tesseract
  mkdir include\leptonica
  xcopy "tesseract\build\bin\Release\tesseract*.dll" .\include\tesseract\tesseract.dll
  xcopy "tesseract\build\bin\Release\*leptonica*.dll" .\include\leptonica\leptonica.dll

  cd python-tesseract-sip
  "%PYTHON%/python.exe" setup.py bdist_wheel

test_script:
- dir
- dir dist
- dir build

artifacts:
- path: python-tesseract-sip\dist\*.whl
  name: wheels