environment:
  matrix:
  - PYTHON: "C:/Python35"
    BUILD_ENV: "Visual Studio 14"
    BUILD_DIR: "build"
    PYTHON_VERSION: "3.5"
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - |
    dir "C:\Program Files (x86)\"
    git submodule update --init --recursive
    "%PYTHON%/python.exe" find_version.py
    "%PYTHON%/python.exe" -m pip install --upgrade pip
    "%PYTHON%/python.exe" -m pip install -r requirements.txt

    curl -fsS -L -o sip-4.19.zip https://sourceforge.net/projects/pyqt/files/sip/sip-4.19/sip-4.19.zip
    7z x sip-4.19.zip
    dir
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"

before_build:
- |
  cd tesseract
  curl -fsS -L -o cppan.zip https://cppan.org/client/cppan-master-Windows-client.zip
  7z x cppan.zip
  set PATH=%PATH%;%cd%
  cppan

- ps: $blockRdp = $true;

- ps: 'Add-Content $env:USERPROFILE\.cppan\cppan.yml "`n`nvar_check_jobs: 1`n"'
- ps: 'Add-Content $env:USERPROFILE\.cppan\cppan.yml "`n`nbuild_warning_level: 0`n"'
- ps: 'Add-Content $env:USERPROFILE\.cppan\cppan.yml "`n`nbuild_system_verbose: false`n"'

- |
  cd ../sip-4.19
  dir
  "%PYTHON%/python.exe" configure.py  --platform win32-msvc2015
  nmake
  nmake install
  cd ..
  dir


build_script:
- |
  cd tesseract
  mkdir build
  cd build
  cmake .. -G "%BUILD_ENV%" -DBUILD_TRAINING_TOOLS=Off -DAPPVEYOR=1
  cmake --build . --config Release

  cd ../..
  mkdir include\tesseract
  mkdir include\leptonica
  for /r "tesseract\" %%a in (*.h) do @copy /y "%%a" include\tesseract\
  xcopy "tesseract\build\bin\Release\tesseract*.dll" .\include\tesseract\tesseract.dll /I
  xcopy "tesseract\build\bin\Release\*leptonica*.dll" .\include\leptonica\leptonica.dll /I

  cd python-tesseract-sip
  "%PYTHON%/python.exe" setup.py bdist

test_script:
- dir
- dir dist
- dir build

artifacts:
- path: python-tesseract-sip\dist\*.whl
  name: wheels