from setuptools import setup
from setuptools.dist import Distribution
import pip
import os
import sys
import io

long_description = ""

with io.open('README.md', encoding="utf-8") as f:
    long_description = f.read()

# cv_version.py should be generated by running find_version.py
from cv_version import ts_version

#numpy_version = ""

# Get required numpy version
#for package in pip.get_installed_distributions():
#    if package.key == "numpy":
#        numpy_version = package.version

class BinaryDistribution(Distribution):
    """ Forces BinaryDistribution. """
    def has_ext_modules(self):
        return True

    def is_pure(self):
        return False

package_data = {}

if os.name == 'posix':
    package_data['tesseract'] = ['*.so']
else:
    package_data['tesseract'] = ['*.pyd', '*.dll']

setup(name='easy-ocr',
      version=ts_version,
      url='https://github.com/glitchassassin/easy-ocr',
      license='MIT',
      description='Wrapper package for Tesseract python bindings.',
      long_description=long_description,
      distclass=BinaryDistribution,
      packages=['cv2'],
      package_data=package_data,
      maintainer="Jon Winsley",
      include_package_data=True,
      classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'Intended Audience :: Education',
        'Intended Audience :: Information Technology',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: MIT License',
        'Operating System :: Microsoft :: Windows',
        'Programming Language :: Python',
        'Programming Language :: C++',
        'Programming Language :: Python :: Implementation :: CPython',
        'Topic :: Scientific/Engineering',
        'Topic :: Scientific/Engineering :: Image Recognition',
        'Topic :: Software Development',
        ]
      )